#3 The Newyork times cloned project
chubaquelo/NYtimes-Clone-Project pull request #3
Opened 2020-08-24 16:15 UTC by guillainbisimwa

In this project, we have cloned the new york times website (https://www.nytimes.com/).
We have used flex, grid, and float properties and have styled it like the original one.

2020-08-24 17:52 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

### However, we need to work on some changes before we can merge.

#### IMPORTANT! 
- Please **DO NOT** close/merge PRs from previous reviews. It introduces confusion when reviewing and contexts are often lost. This is considered very unprofessional. Please keep this in mind from your next projects.

_You will find additional comments below._

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-08-24 17:52 UTC, tirthajyoti-ghosh commented on style.css
> +/* stylelint-disable */
Please remove this line. You are preventing stylelint from checking any errors/bad practices in this file.

2020-08-24 17:52 UTC, tirthajyoti-ghosh commented on style.css
> +   max-width: 75px !important;
Please remove `!important` from CSS rule. Use more specific selectors to override styles.

2020-08-24 17:52 UTC, tirthajyoti-ghosh commented on style.css
> +    grid-template-rows: 2;
Add a unit after the value. Right now it is invalid.

![image](https://user-images.githubusercontent.com/57726348/91078518-5ffebb80-e660-11ea-87d7-67fd6071d476.png)

These types of errors would have been caught if you have not prevented stylelint from checking this file.

2020-08-25 00:46 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Don't overuse ID selectors** 
Good job with the improvements for this project :muscle:  :muscle:
Your really looks like the original :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:
- [ ] Don't overuse ID Selectors
- [ ] Don't repeat yourself, in order to minimize code you can group selectors with the same style definition.
- [ ]  Remove the unused class attribute


Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-08-25 00:46 UTC, andresporras3423 commented on index.html
> +        <h1 class="">Space Ripples Reveal Big Bang’s Smoking Gun</h1>
remove unused class attribute

2020-08-25 00:46 UTC, andresporras3423 commented on style.css
> +#most-popular {
Don't overuse ID selectors

2020-08-25 00:46 UTC, andresporras3423 commented on style.css
> +.version-links:hover { text-decoration: none; }
Group with selector on line 212

2020-08-25 00:46 UTC, andresporras3423 commented on style.css
> +.single-pick a:hover { text-decoration: underline; }
Group with selector on line 46

2020-08-25 15:08 UTC, guillainbisimwa commented on style.css
> +.single-pick a:hover { text-decoration: underline; }
How do you suggest to fix this? Because when we group with the selector on line 46 we got linterStyle errors. We need to use one property for a class:hover and a normal class.

2020-08-25 20:17 UTC, MuriloRoque approved these changes
# Status: Approved :green_circle: 

## Hello @guillainbisimwa and @chubaquelo  :wave: 

## Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: 

## You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-08-26 14:39 UTC, merged